### ISSUE TITLE
Include level 0 title so each document is a fully valid document

### ISSUE THREAD

**Issue by DavidGamba** [asciidoctor/asciidoctor-doctest#4]
None of the test documents includes a `= Level 0` heading which means they don't generate a fully valid output document as a result.

In the case of the manpage backend, not having the level 0 means the generated file can't be viewed without manually adding the header.

A tester can add his own adoc input files but it is easier if this is done in the provided examples.

WDYT?

**Comment by jirutka** [comment]
Ah, I finally see what’s the problem! Manpage must start with a `.TH` header to be valid and so you can view the examples group in a manpage viewer.

Well, the `serialize` method in ExamplesSuite always generates a whole example group (i.e. examples file), so you can easily add some `.TH` header here. I suggest to put `group_name` to the  `.TH` header.
