### ISSUE TITLE
Support for Ruby 1.8.7

### ISSUE THREAD

**Issue by DavidGamba** [asciidoctor/asciidoctor-doctest#6]
Hi @jirutka ,

Asciidoctor still supports ruby 1.8.7. I think that they are not dropping that support anytime soon.

Are you thinking on making this work with 1.8.7?

Thanks,

**Comment by jirutka** [comment]
DocTest now supports MRI 2.0.0 and also JRuby 9000-dev. Rubinius doesn’t support keyword arguments yet, so it’s out of game for now.
